# Generated by Django 3.2.9 on 2021-11-04 11:23

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211104_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
